name: Regulatory Document Generation
on: [workflow_dispatch]
jobs:
  rdm-generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install RDM dependencies
        run: |
          sudo apt install pandoc texlive-latex-extra latexmk
          pip3 install --user virtualenv
          python3 -m virtualenv tmp-venv
          source tmp-venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
      - name: Generate release documents
        run: |
          source tmp-venv/bin/activate
          pushd regulatory
          pandoc --version
          pandoc --help
          make all
          make pdfs
          make docs
          popd
      # For now, PDFs are not in use
      # - name: Store PDFs as artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #       name: regulatory-pdfs.zip
      #       path: ./release/*.pdf

      - name: Store docx files as artifacts
        uses: actions/upload-artifact@v2
        with:
            name: regulatory-docs.zip
            path: regulatory/release/*.docx